language: ruby

rvm:
  - 2.4.2
  - 2.4.3

bundler_args: --without production

before_script:
 - chmod +x ./travis/cibuild 

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./travis/cibuild

gemfile:
  - travis/Gemfile

cache: bundler
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  
notifications:
  email: false

sudo: false # route your build to the container-based infrastructure for a faster build

